package com.pg85.otg.client.editor.data;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.*;
import java.util.*;

public class ConfigWriter {

    private static final Logger LOG = LoggerFactory.getLogger(ConfigWriter.class);

    public static boolean save(Path iniPath, List<String> rawLines, List<PropertyValue> properties) {
        Map<String, String> changes = new HashMap<>();
        for (PropertyValue pv : properties) {
            if (pv.isDirty()) {
                changes.put(pv.getDefinition().name(), pv.getValue());
            }
        }

        if (changes.isEmpty()) {
            LOG.info("No changes to save");
            return true;
        }

        List<String> output = new ArrayList<>(rawLines.size());
        for (String line : rawLines) {
            String trimmed = line.trim();

            if (!trimmed.isEmpty() && !trimmed.startsWith("#") && !trimmed.startsWith("<")
                    && !trimmed.contains("(") && trimmed.contains(":")) {
                int colonIdx = trimmed.indexOf(':');
                String key = trimmed.substring(0, colonIdx).trim();

                if (changes.containsKey(key)) {
                    String indent = line.substring(0, line.indexOf(trimmed));
                    output.add(indent + key + ": " + changes.get(key));
                    changes.remove(key);
                    continue;
                }
            }

            output.add(line);
        }

        if (!changes.isEmpty()) {
            output.add("");
            output.add("# Added by OTG Editor");
            for (var entry : changes.entrySet()) {
                output.add(entry.getKey() + ": " + entry.getValue());
            }
        }

        try {
            Files.write(iniPath, output);
            LOG.info("Saved {} changes to {}", properties.stream().filter(PropertyValue::isDirty).count(), iniPath.getFileName());
            return true;
        } catch (IOException e) {
            LOG.error("Failed to write config file: {}", iniPath, e);
            return false;
        }
    }

    public static boolean createFromDefaults(Path path, Map<String, PropertyDefinition> definitions) {
        List<String> lines = new ArrayList<>();
        lines.add("# Generated by OTG Editor");
        lines.add("");

        Map<PropertyCategory, List<PropertyDefinition>> byCategory = new LinkedHashMap<>();
        for (PropertyDefinition def : definitions.values()) {
            byCategory.computeIfAbsent(def.category(), k -> new ArrayList<>()).add(def);
        }

        for (var entry : byCategory.entrySet()) {
            lines.add("# " + entry.getKey().getDisplayName());
            for (PropertyDefinition def : entry.getValue()) {
                String value = def.defaultValue() != null ? def.defaultValue() : "";
                lines.add(def.name() + ": " + value);
            }
            lines.add("");
        }

        try {
            Files.createDirectories(path.getParent());
            Files.write(path, lines);
            LOG.info("Created new config file: {}", path.getFileName());
            return true;
        } catch (IOException e) {
            LOG.error("Failed to create config file: {}", path, e);
            return false;
        }
    }

    /**
     * Save modified BiomeGroup() lines back to the .ini file.
     * Replaces existing group lines, removes deleted groups, appends new groups.
     * Returns updated rawLines for session reuse.
     */
    public static List<String> saveBiomeGroups(Path iniPath, List<String> rawLines, List<BiomeGroupData> groups) {
        Set<String> processedNames = new HashSet<>();
        List<String> output = new ArrayList<>(rawLines.size());
        int lastGroupLineIndex = -1;

        for (int i = 0; i < rawLines.size(); i++) {
            String line = rawLines.get(i);
            String trimmed = line.trim();

            if (trimmed.startsWith("BiomeGroup(") && trimmed.endsWith(")")) {
                String args = trimmed.substring("BiomeGroup(".length(), trimmed.length() - 1);
                String name = args.split(",")[0].trim();

                BiomeGroupData match = null;
                for (BiomeGroupData g : groups) {
                    if (g.getName().equals(name)) {
                        match = g;
                        break;
                    }
                }

                if (match != null) {
                    processedNames.add(name);
                    if (!match.isDeleted()) {
                        output.add(match.toConfigLine());
                        lastGroupLineIndex = output.size() - 1;
                    }
                } else {
                    output.add(line);
                    lastGroupLineIndex = output.size() - 1;
                }
            } else {
                output.add(line);
            }
        }

        List<String> newGroupLines = new ArrayList<>();
        for (BiomeGroupData g : groups) {
            if (!processedNames.contains(g.getName()) && !g.isDeleted()) {
                newGroupLines.add(g.toConfigLine());
            }
        }

        if (!newGroupLines.isEmpty()) {
            int insertAt = lastGroupLineIndex >= 0 ? lastGroupLineIndex + 1 : output.size();
            output.addAll(insertAt, newGroupLines);
        }

        try {
            Files.write(iniPath, output);
            LOG.info("Saved {} biome groups to {}", groups.stream().filter(g -> !g.isDeleted()).count(), iniPath.getFileName());
        } catch (IOException e) {
            LOG.error("Failed to write biome groups to {}", iniPath, e);
        }

        return output;
    }
}
